### PR TITLE
Support mouse button remapping.

### PR DESCRIPTION
**Pull request by nshi**
Remap mouse buttons 3-31 to any other commands. Left/right/middle mouse
buttons cannot be remapped. The keyword for mouse button is "button#"
where # is the button number.

### CODE REVIEW

**Comment by nshi** [comment]
Hi, @koekeishiya. Do you think this patch is useful? Thanks in advance for any feedback you may have.

**Comment by koekeishiya** [comment]
Seems like a useful enhancement, but I'd like to find the time to workout #23 before any additional changes are made.

**Comment by nshi** [comment]
Thanks for looking at this. That makes sense. Let me know if you've any feedback on this after #23 is resolved.

**Comment by dominiklohmann** [comment]
Is issue #23 now considered solved? This seems like a useful feature to have, especially with the `cmd-[` and `cmd-]` mappings suggested.

**Comment by koekeishiya** [comment]
Is there a reason why this implementation does not allow modifiers for mouse-button hotkeys?

**Comment by koekeishiya** [comment]
I'm not really happy with how this implementation was done, so I went ahead and implemented this functionality myself. See #52

**Comment by koekeishiya** [comment]
@nshi @dominiklohmann  I would appreicate if either of you could confirm that the functionaity after my changes on master, and the functionality this PR provided, both work the same for the end-user.

Thanks for bringing this to my attention.

**Pull request closed without merging**
