### PR TITLE
Preserve original KeyEvent flags

### PR DESCRIPTION
**Pull request by choco**
This is needed on Sierra

### CODE REVIEW

**Comment by koekeishiya** [comment]
Hm aight, thanks for letting me know. 
I will be doing this change manually as I am also gonna get rid of the `Press|ReleaseModifier` code.

**Comment by koekeishiya** [comment]
Well this is great stuff Apple, this change breaks El Capitan compatibility.

**Comment by choco** [comment]
Does keeping the `Press|ReleaseModifier` with this change does still break compatibility?

**Comment by koekeishiya** [comment]
> Does keeping the Press|ReleaseModifier with this change does still break compatibility?

Yeah, it breaks regardless if the `Press|ReleaseModifier` is there or not.
I guess last resort is detecting which OS we are running on or something.

**Comment by koekeishiya** [comment]
@choco If you could confirm that the latest master now also works on Sierra, that would be great.

**Comment by choco** [comment]
Yep, seems to work perfectly :D Hopefully next macOS version doesn't break this, but I would speculate that this change will be needed for all future versions, so it would probably be better to check if version is at least Sierra imho.

**Comment by koekeishiya** [comment]
>  but I would speculate that this change will be needed for all future versions, so it would probably be better to check if version is at least Sierra imho.

Probably true, might as well make that change.

**Pull request closed without merging**
